from __future__ import annotations

from dataclasses import asdict
from hashlib import sha256
from importlib.resources import files
import json
from pathlib import Path

from . import __version__
from .config import RepositoryConfig
from .distribution import distribution_identity
from .errors import AgenticRepoError
from .paths import confined_repo_path
from .profiles import load_fragment


GENERATED_MARKER = "<!-- Generated by agentic-repo-kit; edit .agentic-repo.toml, local inputs, or kit profiles instead. -->"


def _template(name: str) -> str:
    return files("agentic_repo_kit").joinpath("templates", name).read_text(encoding="utf-8")


def _local_fragments(root: Path, paths: tuple[str, ...]) -> list[str]:
    fragments: list[str] = []
    for relative in paths:
        path = confined_repo_path(root, relative, label="local input")
        try:
            fragments.append(path.read_text(encoding="utf-8").strip())
        except FileNotFoundError as exc:
            raise AgenticRepoError(f"local input not found: {relative}") from exc
        except IsADirectoryError as exc:
            raise AgenticRepoError(f"local input is not a regular file: {relative}") from exc
    return fragments


def _compose(config: RepositoryConfig, fragment: str, root: Path) -> str:
    parts = [load_fragment(profile, fragment) for profile in config.profiles]
    local_paths = {
        "agents.md": config.local.policy_files,
        "playbook.md": config.local.playbook_files,
        "pr.md": config.local.pr_files,
    }[fragment]
    parts.extend(_local_fragments(root, local_paths))
    return "\n\n".join(part for part in parts if part)


def _replace(template: str, replacements: dict[str, str]) -> str:
    result = template
    for key, value in replacements.items():
        result = result.replace("{{" + key + "}}", value)
    return result.rstrip() + "\n"


def render_generated_files(config: RepositoryConfig, root: Path) -> dict[str, str]:
    confined_repo_path(root, config.project.roadmap, label="project.roadmap")
    common = {
        "MARKER": GENERATED_MARKER,
        "PROJECT_NAME": config.project.name,
        "PROJECT_KIND": config.project.kind,
        "ROADMAP_PATH": config.project.roadmap,
        "PROFILE_LIST": ", ".join(config.profiles),
        "AGENT_SECTIONS": _compose(config, "agents.md", root),
        "PLAYBOOK_SECTIONS": _compose(config, "playbook.md", root),
        "PR_SECTIONS": _compose(config, "pr.md", root),
        "CLOUD_FIRST": "enabled" if config.workflow.cloud_first else "not required",
        "ONE_ITEM_PER_PR": "required",
    }

    generated = {
        "AGENTS.md": _replace(_template("AGENTS.md.tmpl"), common),
        "docs/agent-playbook.md": _replace(_template("agent-playbook.md.tmpl"), common),
        "docs/roadmap-authoring.md": _replace(_template("roadmap-authoring.md.tmpl"), common),
        ".github/pull_request_template.md": _replace(_template("pull_request_template.md.tmpl"), common),
        "CLAUDE.md": _replace(_template("CLAUDE.md.tmpl"), common),
        ".github/copilot-instructions.md": _replace(_template("copilot-instructions.md.tmpl"), common),
    }

    if "reverse-engineering" in config.profiles:
        generated["docs/re/README.md"] = _replace(_template("re-readme.md.tmpl"), common)
        generated["docs/experiments/README.md"] = _replace(_template("experiments-readme.md.tmpl"), common)

    hashes = {path: sha256(content.encode("utf-8")).hexdigest() for path, content in sorted(generated.items())}
    lock = {
        "format": 2,
        "tool_version": __version__,
        "kit_version": config.kit_version,
        "project": asdict(config.project),
        "profiles": list(config.profiles),
        "distribution": distribution_identity(),
        "generated": hashes,
    }
    generated[".agentic-repo.lock.json"] = json.dumps(lock, indent=2, sort_keys=True) + "\n"
    return generated
